import { expect, test } from '@playwright/test';

test('drive totals and selected partitions remain editable, undoable and reusable', async ({ page }) => {
  await page.route('**/api/**', (route) => route.fulfill({ status: 503, json: { error: 'Offline storage fixture' } }));
  await page.goto('/');
  await page.getByRole('button', { name: 'Add widget', exact: true }).click();
  const catalog = page.getByRole('dialog', { name: 'Add widget', exact: true });
  await catalog.getByLabel('Search widgets', { exact: true }).fill('Mounted storage wide');
  await catalog.getByRole('button', { name: 'Add Mounted storage wide', exact: true }).click();
  const card = page.locator('[data-widget-id="mounted-storage-wide"]');
  await expect(card).toContainText('3 drives');
  await expect(card).toContainText('SSD');
  await expect(card).toContainText('NVMe');
  await expect(card).toContainText('HDD');
  await expect(card).not.toContainText('/mnt/games');
  await page.getByRole('combobox', { name: 'Storage view', exact: true }).selectOption('partitions');
  const paths = page.getByRole('textbox', { name: 'Mount paths', exact: true });
  await paths.fill('/\n/mnt/nvme\n/mnt/games');
  await paths.press('Tab');
  await expect(card).toContainText('3 filesystems');
  await expect(card).toContainText('NVMe partition');
  await expect(card).toContainText('Games partition');
  await expect(card).not.toContainText('/boot');
  await expect(card).not.toContainText('/mnt/hdd');
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(card).toContainText('5 filesystems');
  await page.getByRole('button', { name: 'Redo', exact: true }).click();
  await expect(card).toContainText('3 filesystems');
  await paths.fill('relative'); await paths.press('Tab');
  await expect(paths).toHaveAttribute('aria-invalid', 'true');
  await expect(card).toContainText('3 filesystems');
  await paths.focus(); await paths.press('Escape');
  await page.getByRole('button', { name: 'Save as custom widget…', exact: true }).click();
  const save = page.getByRole('dialog', { name: 'Save as custom widget', exact: true });
  await save.getByLabel('Custom widget name', { exact: true }).fill('SSD and NVMe partitions');
  await save.getByRole('button', { name: 'Save widget', exact: true }).click();
  await expect(save).not.toBeVisible();
  await page.getByRole('combobox', { name: 'Storage view', exact: true }).selectOption('drives');
  await expect(card).toContainText('3 drives');
  await page.getByRole('button', { name: 'Add widget', exact: true }).click();
  await catalog.getByLabel('Search widgets', { exact: true }).fill('SSD and NVMe partitions');
  await catalog.getByRole('button', { name: 'Add SSD and NVMe partitions', exact: true }).click();
  const custom = page.getByRole('group', { name: 'Mounted storage card' }).last();
  await expect(custom).toContainText('3 filesystems');
  await expect(custom).toContainText('Games partition');
  await expect(card).toContainText('3 drives');
  await page.screenshot({ path: 'artifacts/storage-views-editor.png', fullPage: true });
});
